/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface RefreshToken {
  created_at: Generated<Date | null>;
  expires_at: Date;
  id: string;
  is_revoked: Generated<number | null>;
  token_hash: string;
  updated_at: Generated<Date | null>;
  user_id: string;
}

export interface User {
  created_at: Generated<Date | null>;
  email: string;
  id: string;
  is_active: Generated<number | null>;
  is_email_verified: Generated<number | null>;
  name: string;
  password: string;
  updated_at: Generated<Date | null>;
}

export interface DB {
  refresh_tokens: RefreshToken;
  users: User;
}
